data "template_file" "server_conf" {
 template = "${file("${path.module}/templates/openvpn.server.conf")}"

 vars {
   openvpn_local_ip_address = "${var.openvpn_local_ip_address}"
   openvpn_port = "${var.openvpn_port}"
   openvpn_protocol = "${var.openvpn_protocol}"
   openvpn_device = "${var.openvpn_device}"
   openvpn_dev_node = "${var.openvpn_dev_node}"
   openvpn_ca_filename = "${var.openvpn_ca_filename}"
   openvpn_cert_filename = "${var.openvpn_cert_filename}"
   openvpn_private_key_filename = "${var.openvpn_private_key_filename}"
   openvpn_diffie_hellman_filename = "${var.openvpn_diffie_hellman_filename}"
   openvpn_network_topology = "${var.openvpn_network_topology}"
   openvpn_server_vpn_subnet = "${var.openvpn_server_vpn_subnet}"
   openvpn_server_vpn_subnet_netmask = "${var.openvpn_server_vpn_subnet_netmask}"
   openvpn_record_pool_persist_filename = "${var.openvpn_record_pool_persist_filename}"
   openvpn_server_bridge_interface = "${var.openvpn_server_bridge_interface}"
   openvpn_server_bridge_interface_netmask = "${var.openvpn_server_bridge_interface_netmask}"
   openvpn_server_bridge_interface_range = "${var.openvpn_server_bridge_interface_range}"
   openvpn_push_client_routes = "${var.openvpn_push_client_routes}"
   openvpn_client_config_dir = "${var.openvpn_client_config_dir}"
   openvpn_enable_server_mode_for_dchp_proxy = "${var.openvpn_enable_server_mode_for_dchp_proxy}"
   openvpn_enable_redirect_gateway = "${var.openvpn_enable_redirect_gateway}"
   openvpn_learn_address_script_path = "${var.openvpn_learn_address_script_path}"
   openvpn_windows_network_settings = "${var.openvpn_windows_network_settings}"
   openvpn_allow_client_to_client_viewing = "${var.openvpn_allow_client_to_client_viewing}"
   openvpn_allow_duplicate_common_name = "${var.openvpn_allow_duplicate_common_name}"
   openvpn_enable_keepalive = "${var.openvpn_enable_keepalive}"
   openvpn_keepalive_ping_seconds = "${var.openvpn_keepalive_ping_seconds}"
   openvpn_keepalive_period_seconds = "${var.openvpn_keepalive_period_seconds}"
   openvpn_tls_auth_secret_key = "${var.openvpn_tls_auth_secret_key}"
   openvpn_cipher = "${var.openvpn_cipher}"
   openvpn_compression = "${var.openvpn_compression}"
   openvpn_enable_compression_for_older_clients = "${var.openvpn_enable_compression_for_older_clients}"
   openvpn_max_concurrent_clients = "${var.openvpn_max_concurrent_clients}"
   openvpn_user = "${var.openvpn_user}"
   openvpn_group = "${var.openvpn_group}"
   openvpn_enable_persist_key = "${var.openvpn_enable_persist_key}"
   openvpn_enable_persist_tun = "${var.openvpn_enable_persist_tun}"
   openvpn_status_filename = "${var.openvpn_status_filename}"
   openvpn_log_filename = "${var.openvpn_log_filename}"
   openvpn_log_enable_append = "${var.openvpn_log_enable_append}"
   openvpn_log_verbosity = "${var.openvpn_log_verbosity}"
   openvpn_slience_repeat_messages = "${var.openvpn_slience_repeat_messages}"
   openvpn_notify_client_on_restart = "${var.openvpn_notify_client_on_restart}"
 }
}
